AWSTemplateFormatVersion: 2010-09-09
Description: >-
  driving-manager
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  # The name of the Cognito User Pool to use for authentication
  CognitoUserPoolArn:
    Type: String
    Description: The ARN of the Cognito User Pool to use for authentication
    Default: '{{resolve:ssm:CognitoUserPoolArn:1}}'
  CorsAllowOrigin:
    Type: String
    Description: The origin to allow for CORS requests
    Default: "'{{resolve:ssm:DrivingManagerFrontendUrl:1}}'"
  CorsAllowHeaders:
    Type: String
    Description: The headers to allow for CORS requests
    Default: "'Content-Type,Authorization'"
  CorsAllowMethods:
    Type: String
    Description: The methods to allow for CORS requests
    Default: "'GET,POST,PUT,DELETE,OPTIONS'"


# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
    Runtime: nodejs22.x
    Architectures:
    - x86_64
    MemorySize: 128
    Timeout: 100
    Environment:
      Variables:
        # Make table name accessible as environment variable from function code during execution
        CHECK_ANSWERS_TABLE: !Ref CheckAnswersTable
        DRIVING_SESSIONS_TABLE: !Ref DrivingSessionsTable
        ALLOW_ORIGIN: !Ref CorsAllowOrigin
        ALLOW_HEADERS: !Ref CorsAllowHeaders
        ALLOW_METHODS: !Ref CorsAllowMethods
  Api:
    TracingEnabled: true
    Auth:
      DefaultAuthorizer: MyCognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        MyCognitoAuthorizer:
          UserPoolArn: !Ref CognitoUserPoolArn
    Cors:
      AllowOrigin: !Ref CorsAllowOrigin
      AllowHeaders: !Ref CorsAllowHeaders
      AllowMethods: !Ref CorsAllowMethods

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  checkPostAnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/check/post-answer.postAnswerHandler
      Description: save the answer
      Policies:
      - DynamoDBWritePolicy:
          TableName: !Ref CheckAnswersTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /check/post-answer
            Method: POST
    Metadata:   
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: false
        Banner:
          - js=import path from 'path';
            import { fileURLToPath } from 'url';
            import { createRequire as topLevelCreateRequire } from 'module';
            const require = topLevelCreateRequire(import.meta.url);
            const __filename = fileURLToPath(import.meta.url);
            const __dirname = path.dirname(__filename);

  sessionPutStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/session/put-start.putStartHandler
      Description: save the start record of a driving session
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref DrivingSessionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /session/put-start
            Method: PUT
    Metadata:   
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        Banner:
          - js=import path from 'path';
            import { fileURLToPath } from 'url';
            import { createRequire as topLevelCreateRequire } from 'module';
            const require = topLevelCreateRequire(import.meta.url);
            const __filename = fileURLToPath(import.meta.url);
            const __dirname = path.dirname(__filename);

  sessionPutEndFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/session/put-end.putEndHandler
      Description: save the end record of a driving session
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref DrivingSessionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /session/put-end
            Method: PUT
    Metadata:   
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        Banner:
          - js=import path from 'path';
            import { fileURLToPath } from 'url';
            import { createRequire as topLevelCreateRequire } from 'module';
            const require = topLevelCreateRequire(import.meta.url);
            const __filename = fileURLToPath(import.meta.url);
            const __dirname = path.dirname(__filename);

  sessionGetMonthlyRecordsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/session/get-monthly-records.getMonthlyRecordsHandler
      Description: get monthly driving session records
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref DrivingSessionsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /session/get-monthly-records
            Method: GET
    Metadata:   
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: false
        Banner:
          - js=import path from 'path';
            import { fileURLToPath } from 'url';
            import { createRequire as topLevelCreateRequire } from 'module';
            const require = topLevelCreateRequire(import.meta.url);
            const __filename = fileURLToPath(import.meta.url);
            const __dirname = path.dirname(__filename);

  CheckAnswersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-CheckAnswers"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: date_time
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: date_time
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 5
        MaxWriteRequestUnits: 5

  DrivingSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-DrivingSessions"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: date_number
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: date_number
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      OnDemandThroughput:
        MaxReadRequestUnits: 5
        MaxWriteRequestUnits: 5



  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

